cacheFolder: './.yarn/cache'
patchFolder: './.yarn/patches'

checksumBehavior: update

cloneConcurrency: 1

enableScripts: true

networkConcurrency: 1

nmHoistingLimits: 'dependencies' # workspaces

enableImmutableCache: false

enableGlobalCache: false

enableInlineBuilds: true

nodeLinker: 'node-modules'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.5.0.cjs
