# main menu navigation
menu:
  Home: /
  About: /about
  Archive: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  zhihu:
  twitter:
  facebook: /dimaslanjaka1
  linkedin:
  instagram:
  github: dimaslanjaka

user:
  name: dimaslanjaka
  avatar:
  location: Surabaya, Indonesia
  description: May the Force be with you
  footnotes: # footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: false
  repo: dimaslanjaka/static-blog-generator # your blog repo

# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
  enable: true
  url: https://www.webmanajemen.com/ # the url of your website main domain like this https://xxx.xxx/
  name: dimaslanjaka # the short name in disqus
  decode: true

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: /favicon.ico

friend_links:
  - title: Facebook
    link: https://www.facebook.com/dimaslanjaka1
  - title: Github
    link: https://www.github.com/dimaslanjaka
  - title: Facebook Group
    link: https://www.facebook.com/groups/167869813590708
#  - title: Twitter
#    link: https://twitter.com/

# Google Analytics
ga_track_id: UA-106238155-1
ga_domain:

# Baidu Analytics
ba_track_id:

# picture of about page
about_pic: /images/about-us.png

image_zoom:
  enable: true
