nav:
  - text: About
    link: /about
  - text: Privacy Policy
    link: https://www.webmanajemen.com/p/privacy.html
  - text: Terms Of Service
    link: https://www.webmanajemen.com/p/tos.html
  - text: Contact
    link: /contact
  - text: Games
    submenu:
      - text: "Quiz The Legend Of Neverland"
        link: "https://www.webmanajemen.com/The%20Legend%20Of%20Neverland/Quiz.html"
      - text: "PHP Proxy Hunter"
        link: "https://sh.webmanajemen.com/proxyManager.html"
      - text: "Python Proxy Hunter"
        link: "https://sh.webmanajemen.com:8443/proxy/"
        divider: true
nav_icon: /logo.svg
gallery: true
