# Top navigation menu links
nav:
  - text: Site Overview
    submenu:
      - text: About
        link: /about
      - text: Privacy Policy
        link: https://www.webmanajemen.com/p/privacy.html
      - text: Terms Of Service
        link: https://www.webmanajemen.com/p/tos.html
      - text: Contact
        link: /contact
  - text: HexoJS
    submenu:
      - text: hexo-adsense
        link: https://www.webmanajemen.com/docs/hexo-adsense/
      - text: hexo-shortcodes
        link: https://www.webmanajemen.com/docs/hexo-shortcodes/
      - text: hexo-seo
        link: https://github.com/dimaslanjaka/hexo-seo
  - text: Games
    submenu:
      - text: "Quiz The Legend Of Neverland"
        link: "https://www.webmanajemen.com/The%20Legend%20Of%20Neverland/Quiz.html"
      - text: "Chimeraland Blacklist Player"
        link: "https://www.webmanajemen.com/chimeraland/blacklist-player.html"
  - text: Utilities
    submenu:
      - text: "PHP Proxy Hunter"
        link: "https://sh.webmanajemen.com/proxyManager.html"
      - text: "Python Proxy Hunter"
        link: "https://sh.webmanajemen.com:8443/proxy/"
      - text: "Android Flashtool Utility"
        link: "/android-engineer"
        divider: true
# Footer navigation menu links
footer_nav:
  - text: About
    link: /about
  - text: Privacy Policy
    link: https://www.webmanajemen.com/p/privacy.html
  - text: Terms Of Service
    link: https://www.webmanajemen.com/p/tos.html
  - text: Contact
    link: /contact
# Top navbar icon
nav_icon: /logo.svg
# Show gallery images after post/page
gallery: true
# Show loading animation before page fully loaded
loading_animation:
  enable: true
  # type mini: small loader fixed on top right
  # type full: full page loader
  type: mini