nav:
  - text: About
    link: /about
  - text: Privacy Policy
    link: https://www.webmanajemen.com/p/privacy.html
  - text: Terms Of Service
    link: https://www.webmanajemen.com/p/tos.html
  - text: Contact
    link: /contact
  - text: Sub Menu
    submenu:
      - text: "Sub Menu 1"
        link: "#"
      - text: "Sub Menu 2"
        link: "#"
      - text: "Sub Menu 3"
        link: "#"
        divider: true
nav_icon: https://flowbite.com/docs/images/logo.svg
gallery: true
