# Navigation menu links
# footer navigation not support submenu yet, just print single navigation link.
nav:
  - text: About
    link: /about
  - text: Privacy Policy
    link: https://www.webmanajemen.com/p/privacy.html
  - text: Terms Of Service
    link: https://www.webmanajemen.com/p/tos.html
  - text: Contact
    link: /contact
  - text: Sub Menu
    submenu:
      - text: "Sub Menu 1"
        link: "#"
      - text: "Sub Menu 2"
        link: "#"
      - text: "Sub Menu 3"
        link: "#"
        divider: true
# Top navbar icon
nav_icon: https://flowbite.com/docs/images/logo.svg
# Show gallery images after post/page
gallery: true
# Show loading animation before page fully loaded
loading_animation:
  enable: true
  # type mini: small loader fixed on top right
  # type full: full page loader
  type: mini
